{
  "comments": [
    {
      "key": {
        "uuid": "QYSHvLkE",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 15,
      "author": {
        "id": 1002666
      },
      "writtenOn": "2013-02-27T20:47:06Z",
      "side": 1,
      "message": "Are you sure this doesn\u0027t prevent rescheduling in cases where it will succeed? What kinds of errors cause jgit to throw this exception?",
      "revId": "dfb3259793c93e54e86a38f87ec92fe7abca4a28",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "QcRHv7EA",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 15,
      "author": {
        "id": 1010992
      },
      "writtenOn": "2013-02-28T01:41:23Z",
      "side": 1,
      "message": "jgit will throw this exception while receive pack of remote repository, it receives \"ERR \" string in its input stream, as this exception\u0027s comment said, remote repository has a problem as that it cannot be accessed.",
      "parentUuid": "QYSHvLkE",
      "revId": "dfb3259793c93e54e86a38f87ec92fe7abca4a28",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "QYQHU6jc",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 15,
      "author": {
        "id": 1002666
      },
      "writtenOn": "2013-02-28T13:00:31Z",
      "side": 1,
      "message": "And receiving \"ERR\" string once means you are guaranteed to continue getting \"ERR\" each retry?",
      "parentUuid": "QcRHv7EA",
      "revId": "dfb3259793c93e54e86a38f87ec92fe7abca4a28",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "QtM7uY0M",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 15,
      "author": {
        "id": 1010992
      },
      "writtenOn": "2013-03-04T03:30:55Z",
      "side": 1,
      "message": "Currently at least for errors \"access denied, repository not exported or not found\" we know it will continue getting \"ERR\", and it will be rescheduled again and again, never end. If we know some \"ERR\"s are recoverable at a later time, we can add code to distinguish them then.",
      "parentUuid": "QYQHU6jc",
      "revId": "dfb3259793c93e54e86a38f87ec92fe7abca4a28",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    }
  ]
}